### ISSUE TITLE
Probe baud rates...

### ISSUE THREAD

**Issue by WestfW** [wholder/ArduinoReader#1]
A major source of problems with uploading code to Arduinos is when the AVR clockrate turns out to be incorrect.  If you could add a feature that probes different "likely" bitrates and checks for appropriate responses, that would be very useful.  ("Likely" for an Uno is 115200, 57600 (accidental or intentional use of internal 8MHz oscillator), 14400 (div8 fuse left programmed), and 7200 (div8+8MHz.)  But YMMV.)

**Comment by wholder** [comment]
Thanks.  That's a good suggestion.  The code already has a loop where it
tries the different protocols to determine which one "bites" on the reset
hook.  The only downside I see is that it will take longer to cycle around
to trying the other protocols, which can lead to some significant pauses.
But, with some tuning, perhaps I can minimize that.  It also might help if
I added a status display to show what the code was doing during the pause.

On a different note, now that my disassembler seems to be working, I've
started to examine the different boot loaders on the boards in my Arduino
collection and noticed a curious thing in a version of Optiboot (I think) I
found on a Sparkfun RedBoard.  The beginning of the code on the RedBoard
looks like this:

7E00:   2411  eor   r1,r1
7E02:   B784  in    r24,0x34
7E04:   BE14  out   0x34,r1
7E06:   FF81  sbrs  r24,1
7E08:   D0F0  rcall 7FEA

But, when I disassemble the code for the latest version of Optiboot, 8,0, I
get this:

7E00:   C001  rjmp  7E04
7E02:   C0DC  rjmp  7FBC
7E04:   2411  eor   r1,r1
7E06:   B784  in    r24,0x34
7E08:   2388  and   r24,r24

I'm not sure which version of Optiboot is used on the RedBoard, but I'm
curious as to why Optiboot 8.0 added a jump for the INT0 interrupt vector?
As near as I can tell, the handler seems to be using SPM instructions to to
store something into program memory, but I haven't yet puzzled out why.

Also, I notice that there are an additional 19 words available at the end
of the 328P version of Optiboot 8.0, which has me wondering if there might
be a way to shoehorn in code to process the read fuses request.  I suppose
only my code really cares, but being able to read the value of the fuses
makes it possible to determine the exact size an offset of the boot loader.

Wayne

**Comment by WestfW** [comment]
7E00: 2411 eor r1,r1
7E02: B784 in r24,0x34

But, when I disassemble the code for the latest version of Optiboot, 8,0, I
get this:

7E00: C001 rjmp 7E04
7E02: C0DC rjmp 7FBC
7E04: 2411 eor r1,r1
7E06: B784 in r24,0x34
7E08: 2388 and r24,r24

I'm not sure which version of Optiboot is used on the RedBoard, but I'm
curious as to why Optiboot 8.0 added a jump for the INT0 interrupt vector? 


It's not an interrupt vector - Optiboot doesn't use interrupts, and so the code just starts "immediately" at 0x7E00, as you see in the pre-8.0 boards.  In 8.0, we add the vector at 7E02 to jump to the "do_spm" code.This allows application code to do a "call 7E02" (or similar), and have code in the bootloader execute an "spm" instruction on its behalf.  SPM only works from within the bootloader section, so this is a way to permit an application to write flash pages.
There's an example here: test_dospm example
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Optiboot/optiboot
 Small and Fast Bootloader for Arduino and other Atmel AVR chips - Optiboot/optiboot  |   |

  |

  |

**Comment by wholder** [comment]
Ah, that makes sense.  Thanks for the explanation. I guess I'll need to get
more familiar with the SPM instruction and the special cases that apply to
code placed in the boot section.  Your dospm example didn't make it through
gmail, but I went and looked it up.  Thanks for the reference.  I'm not
sure what I'd use for, but it's always good to have more options.

BTW, I decided to try and read out the boot code using a sketch running on
the board.  This worked fine with a board running Optiboot 8.0, but when I
tried to read the boot section on an Arduino Mega 2560, I found that the
lock bits were set to prevent reading from the boot area.  Do you have any
idea why they decided to do this? And, do you know of any other boards, or
boot loaders that set the lock bits to deny read access to the boot loader?

And, if you don't mind me asking more questions... With the Arduino UNO,
they decided to replace the FTDI chip with an ATMega16U2.  But it seems to
me like they missed an opportunity doing this when they could have
programed the ATMega16U2 to act as an ISP programmer for the Atmega328P and
completely avoided the need for a boot loader.  Or, even if they kept the
boot loader, this would have provided a way for the board to burn its own
boot loader.  Does this make sense, or am I missing something?

Wayne

**Comment by WestfW** [comment]
BTW, I decided to try and read out the boot code using a sketch running on
the board. This worked fine with a board running Optiboot 8.0, but when I
tried to read the boot section on an Arduino Mega 2560, I found that the
lock bits were set to prevent reading from the boot area. Do you have any
idea why they decided to do this?

Fear.  Back when I submitted the changes/fixes that resulted in v4.4, I included a change of the lock bits from 0F to 2F, precisely so that the application could tell which bootloader was loaded.  The Arduino team switched it back.  Here's the resulting message exchange (with commit links!):
From: "David A. Mellis" <dam@mellis.org>
To: William Chops Westfield <westfw@mac.com>

There's not a great reason, except that when I read the descriptions
of the lock bits in the data sheet, it sounded like there was some
effect on the interrupt vectors too.  I didn't quite understand all
the implications, and didn't have time to dig into it, so I thought it
was safer to keep the bits as they were.

On Thu, Nov 10, 2011 at 11:33 AM, William "Chops" Westfield wrote:
> https://github.com/arduino/Arduino/commit/e7ff92876267e0057ba1407467a2484ca1a0d60d
>
> Sets the fuse bits back to read-protecting the bootloader from the
> application sections.
> How come?
>   https://github.com/arduino/Arduino/commit/61e4d16675ad64ba82c85239567c6e86c10e775a
> (committed earlier the same day) had intentionally set them to allow reads
> so that sketches (for example "fusebytes.pde") could do a sort of "complete
> status report" of the state of the chip WRT fuses and bootloader...
>
> (Granted, with the fix to allow optiboot to report the correct version to
> avrdude, this is less important, but I was hoping for "service groups" to be
> able to get the info without having to walk a user through fiddling with
> avrdude or parsing the output from a verbose upload. =A0I couldn't think of
> any reason for the bootloader section NOT to be readable; did I miss
> something?)
>
> BillW
>



And, do you know of any other boards, orboot loaders that set the lock bits to deny read access to the boot loader?


No, although I don't "keep up" that much with other bootloaders.   There are various "secure" bootloaders that I imagine would do this, just out of general principles - they might even contain private keys.

And, if you don't mind me asking more questions... With the Arduino UNO,
they decided to replace the FTDI chip with an ATMega16U2. But it seems to
me like they missed an opportunity doing this when they could have
programed the ATMega16U2 to act as an ISP programmer for the Atmega328P and
completely avoided the need for a boot loader. Or, even if they kept the
boot loader, this would have provided a way for the board to burn its own
boot loader. Does this make sense, or am I missing something?

I have wondered about that myself.It would mean three additional pins that would have "odd" behavior during upload (and perhaps afterward), due to the connection to the 16u2, possibly interfering with other SPI devices connected to the Uno.  Users already have problems with the Serial pins, and the pin13 "blink" that the bootloader does.It would also mean losing a bit of backward/sideward compatibility with boards that didn't use a 16u2 (like the Nano.)I'm don't think that the 16u2 supports enough USB "endpoints" to be an ISP programmer and a serial port at the same time, making for interesting "switch-over" problems (arguably, not any worse than the 1200bps reset hack.  (but that came later.))(next: why doesn't the 16u2 tri-state its TXD pin when there is no USB connection, to make the Uno RXD pin less 'contaminated'?  Don't know that one, either...)
BillW

**Comment by wholder** [comment]
I've checked in a change where the STK500V1 protocol will now try multiple baud rates (115200, 57600 and 19200), but always first tries the rate selected in then menu.

**Comment by wholder** [comment]
>  I didn't quite understand all
> the implications, and didn't have time to dig into it, so I thought it
> was safer to keep the bits as they were.

Hmm, safer to go with an approach where he didn't understand the
implications?  Quite odd.  But, having followed the Developers list for
many years, it seems like the kind of response I would expect, as I've
never quite figured out the logic behind some of the decisions the Arduino
core team makes.

> don't think that the 16u2 supports enough USB "endpoints" to be an ISP
programmer
> and a serial port at the same time

The datasheet says it supports 4 endpoints, but I'm not enough of an expert
on USB to know whether that's enough.  But, I'd be happy if there was just
a jumper on the board I could set to select whether the 16u2 acted as an
ISP programmer for the 328, or as a serial adapter the way it does now.

> next: why doesn't the 16u2 tri-state its TXD pin when there is no USB
connection

No.  I didn't know that, but it might explain a few odd things I've seen
with serial IO on the UNO.  Thanks for pointing that out.

I think after all the things I've discovered during my explorations in
Arduino Boot Loaders that I'm going to consider switching over to Optiboot
for all my Arduino projects, as I think that will simplify things
considerably.  I've already done this for several projects where I needed a
bit of extra space, but I like the idea of selecting by "processor" type
and MHz rather than by "board" type, as the Boards menu has gotten so
complicated due to all the variants out there.

It would also be nice to have a simple way to select unusual clock speeds,
such as 15.36 MHz.  This is very useful for projects that need to use the
timers to precisely generate a frequency
<https://sites.google.com/site/wayneholder/controlling-time-2> such as
60,000 Hz.  Fortunately, 15.36 MHz is close enough to 16 MHz that the
standard boot loader seems work, but there are other cases where this is
not true.

Wayne

**Comment by WestfW** [comment]
I like the idea of selecting by "processor" type
and MHz rather than by "board" type, as the Boards menu has gotten so
complicated due to all the variants out there.


Agreed.  However, that's more of an MCUDude board support thing (MiniCore, etc) than Optiboot itself.The main Optiboot repository is leaning away from providing specific .hex files.(The downside, of course, is that MiniCore has 1500+ bootloader .hex files.  MightyCore has over 4500!)

It would also be nice to have a simple way to select unusual clock speeds,
such as 15.36 MHz. This is very useful for projects that need to use the
timers to precisely generate a frequency
It's easy to build a version with a custom clock frequency from source:
 WWHackintosh<9994>  make atmega328 AVR_FREQ=15360000
avr-gcc (AVR_8_bit_GNU_Toolchain_3.6.1_495) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

BAUD RATE CHECK: Desired: 115200, Real: 112941, UBRRL = 16, Difference=-1.9%
avr-gcc -g -Wall -Os -fno-split-wide-types -mrelax -mmcu=atmega328p -DF_CPU=15360000  -DBAUD_RATE=115200 -DLED_START_FLASHES=3            -c -o optiboot.o optiboot.c
avr-gcc -g -Wall -Os -fno-split-wide-types -mrelax -mmcu=atmega328p -DF_CPU=15360000  -DBAUD_RATE=115200 -DLED_START_FLASHES=3          -Wl,--section-start=.text=0x7e00 -Wl,--section-start=.version=0x7ffe -Wl,--relax -nostartfiles -o optiboot_atmega328.elf optiboot.o 
avr-size optiboot_atmega328.elf
   text    data     bss     dec     hex filename
    478       0       0     478     1de optiboot_atmega328.elf


See "make help" :-)
BillW
